image:
  repository: timescale/timescaledb
  tag: latest-pg18-oss
  pullPolicy: IfNotPresent

postgresql:
  username: postgres # name of super user
  password: secretpassword # password for super user

init:
  enabled: false
  init_user_db: |
    -- Create schemata and users
    CREATE EXTENSION IF NOT EXISTS timescaledb;
    CREATE USER myappdb WITH PASSWORD 'password';    
    -- prevent deleting existing db by creating a new one
    SELECT 'CREATE DATABASE myappdb owner myappdb' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'myappdb')\gexec

  init_tables: |  
    \connect myappdb
    CREATE TABLE IF NOT EXISTS metrics (
      time TIMESTAMPTZ NOT NULL,
      value DOUBLE PRECISION NULL
    );
    SELECT create_hypertable('metrics', 'time', if_not_exists => TRUE);

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  size: 20Gi
  storageClass: ""

resources: {}