image:
  repository: timescale/timescaledb-ha
  tag: pg17
  pullPolicy: IfNotPresent

postgresql:
  username: postgres # name of super user
  password: secretpassword # password for super user

init:
  enabled: false
  init_user_db: |
    -- Create schemata and users
    CREATE EXTENSION IF NOT EXISTS timescaledb;
    CREATE USER myappdb WITH PASSWORD 'password';    
    CREATE DATABASE "myappdb" owner myappdb;

  init_tables: |  
    \connect myappdb
    CREATE TABLE IF NOT EXISTS metrics (
      time TIMESTAMPTZ NOT NULL,
      value DOUBLE PRECISION NULL
    );
    SELECT create_hypertable('metrics', 'time', if_not_exists => TRUE);

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  size: 20Gi
  storageClass: ""

resources: {}