name: Create release

# Creating maven and github release

on:
  workflow_dispatch:
    inputs:
      versionChoice:
        type: choice
        required: true
        description: Version Change
        options:
        - patch
        - minor
        - major
      release-version: # id of input
        description: "semver release version e.g. with 0.1.0-1"
        required: false

permissions:
  contents: write
  packages: read

env:
  RELEASE_VERSION: ${{ github.event.inputs.release-version }}
  DOCKERHUB_USERNAME: starwit
  DOCKERHUB_ORG: starwitorg  

jobs:
  build:
    name: "Creating github release"
    runs-on: [self-hosted, linux, X64]
    
    steps:
    - name: Install GH CLI
      uses: dev-hanz-ops/install-gh-cli-action@v0.2.0

    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: create new version
      run: |
        if [ -z "${{ env.RELEASE_VERSION }}" ] 
        then
          NEW_VERSION=$(./.github/workflows/get_version.sh ${{ inputs.versionChoice }})
          echo RELEASE_VERSION=$NEW_VERSION >> $GITHUB_ENV
        fi
        sed -i -E "s/^version:.*/version: $NEW_VERSION/" timescaledb/Chart.yaml
        sed -i -E "s/^version:.*/version: $NEW_VERSION/" postgres/Chart.yaml
        echo "git add ."
        git add .
        modifications=$(git status | grep "modified" || true)
        if [ ! -z "$modifications" ]
        then
          echo "modifications found: $modifications"
          git commit -m "modified version $NEW_VERSION in Chart.yaml" timescaledb/Chart.yaml postgres/Chart.yaml
          git push
        fi

    - name: Create github release
      run: gh release create ${{ env.RELEASE_VERSION }} -F CHANGELOG.md
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout tag
      run: |
        git pull --tags
        git checkout ${{ env.RELEASE_VERSION }}

  publish_helm:
    name: "Publish helm charts"
    needs: build
    runs-on: [self-hosted, linux, X64]
    
    steps:
    - name: get helm
      uses: azure/setup-helm@v4

    - name: login to Helm registry
      run: helm registry login registry-1.docker.io -u starwit -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: get version number
      working-directory: timescaledb
      run: |
        echo RELEASE_VERSION=$(grep version: Chart.yaml | head -1 | awk '{print $2}') >> $GITHUB_ENV

    - name: run helm update
      working-directory: timescaledb
      run: helm dep update

    - name: run helm package
      run: helm package timescaledb

    - name: run helm push
      run: helm push timescaledb-chart-${{ env.RELEASE_VERSION }}.tgz oci://registry-1.docker.io/starwitorg

    - name: run helm update
      working-directory: postgres
      run: helm dep update

    - name: run helm package
      run: helm package postgres

    - name: run helm push
      run: helm push postgres-chart-${{ env.RELEASE_VERSION }}.tgz oci://registry-1.docker.io/starwitorg