name: Create release

# Creating maven and github release

on:
  workflow_dispatch:
    inputs:
      versionChoice:
        type: choice
        required: true
        description: Version Change
        options:
        - patch
        - minor
        - major
      release-version: # id of input
        description: "semver release version e.g. with 0.1.0-1"
        required: false

permissions:
  contents: write
  packages: read

env:
  RELEASE_VERSION: ${{ github.event.inputs.release-version }}
  DOCKERHUB_USERNAME: starwit
  DOCKERHUB_ORG: starwitorg  

jobs:
  build:
    name: "Creating github release"
    runs-on: [self-hosted, linux, X64]
    
    steps:
    - name: Install GH CLI
      uses: dev-hanz-ops/install-gh-cli-action@v0.2.0

    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: create new version in version.txt
      run: |
        if [ -z "${{ env.RELEASE_VERSION }}" ] 
        then
          echo RELEASE_VERSION=$(./get_version.sh ${{ inputs.versionChoice }}) >> $GITHUB_ENV
        fi
      env:
        VERSION: ${{ inputs.versionChoice }}

    - name: Create github release
      run: gh release create ${{ env.RELEASE_VERSION }} -F CHANGELOG.md
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout tag
      run: |
        git pull --tags
        git checkout ${{ env.RELEASE_VERSION }}

  publish_helm:
    name: "Publish helm chart"
    needs: build
    runs-on: [self-hosted, linux, X64]
    
    steps:
    - name: get helm
      uses: azure/setup-helm@v4

    - name: login to Helm registry
      run: helm registry login registry-1.docker.io -u starwit -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: get version number
      working-directory: timescaledb
      run: |
        yq eval ".version = ${{ env.RELEASE_VERSION }}" -i Chart.yaml

    - name: run helm update
      working-directory: timescaledb
      run: helm dep update

    - name: run helm package
      run: helm package timescaledb

    - name: run helm push
      run: helm push timescaledb-chart-${{ env.RELEASE_VERSION }}.tgz oci://registry-1.docker.io/starwitorg